#use visual studio code for requests
@hostname = localhost

@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

@token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoYXNhbi5rYXJhIiwiaWF0IjoxNjUzMDM1OTU1LCJleHAiOjE2NTM4OTk5NTV9.Mer-ASa5hirUCS00T2VEIP0hRCFLNAXMDEgbWFYnqsoTWKfIvQa5F-iztoeR8kC56lVEUjHfJIJEsTxqHWj5uA
POST http://{{host}}/api/auth/signin
Content-Type: {{contentType}}

{
    "username": "hasan.kara",
    "password": "123"
}

### Test Not Secured Service
POST http://{{host}}/test/hello

### Test Secured Service
POST http://{{host}}/test/secured
Content-Type: {{contentType}}
Authorization: Bearer {{token}}


### Test Secured Service
POST http://{{host}}/forgot_password/
Content-Type: {{contentType}}

{
    "username": "hasan.kara"
}


### Test Not Secured Service
GET http://{{host}}/forgot_password/id/c1c639ac21fc487aa12d7d8576dd0bd7503caba1e09447c0b9e7c5b8db594b24


### Test Secured Service
POST http://{{host}}/forgot_password/reset/c1c639ac21fc487aa12d7d8576dd0bd7503caba1e09447c0b9e7c5b8db594b24
Content-Type: {{contentType}}

{
    "password": "123",
    "repeatPassword": "123"
}

