@hostname = localhost

@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

@token = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoYXNhbi5rYXJhIiwiaWF0IjoxNjUzNTY5NjkzLCJleHAiOjE2NTQ0MzM2OTN9.5MYBmsWOFhaQBVTUBx39QU5J1bWfXTnzC7B8UoO1elPaVZ85QHl-yW-_h8r_dnPrPeYVCUVv_Pw160u2EP1czA
POST http://{{host}}/api/auth/signin
Content-Type: {{contentType}}

{
    "username": "hasan.kara",
    "password": "***"
}

### Test Not Secured Service
POST http://{{host}}/test/hello

### Test Secured Service
POST http://{{host}}/test/secured
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

